### ISSUE TITLE
"wildfly does not exist" when run "mvn -X wildfly:deploy"

### ISSUE THREAD

**Issue by wirelesss** [jaxio/javaee-lab#1]
I have problems to generate war,
using command line: mvn -X wildfly:deploy
## "wildfly does not exist" when run "mvn -X wildfly:deploy"

LOG:
.........
[INFO] Processing war project
[INFO] Copying webapp webResources [C:\spring_wks_wildfly\javaee7_wildfly_inheritance\src/main/config/wildfly] to [C:\spring_wks_wildfly\javaee7_wildfly_inheritance\target\javaee7_wildfly_inheritance]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.952 s
[INFO] Finished at: 2016-06-06T01:32:03-05:00
[INFO] Final Memory: 17M/159M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.5:war (default-war) on project javaee7_wildfly_inheritance: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.5:war failed: basedir C:\spring_wks_wildfly\javaee7_wildfly_inheritance\src\main\config\wildfly does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: ## **Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.5:war (default-war) on project javaee7_wildfly_inheritance: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.5:war failed: basedir C:\spring_wks_wildfly\javaee7_wildfly_inheritance\src\main\config\wildfly does not exist**
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.5:war failed: basedir C:\spring_wks_wildfly\javaee7_wildfly_inheritance\src\main\config\wildfly does not exist
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 24 more
Caused by: java.lang.IllegalStateException: basedir C:\spring_wks_wildfly\javaee7_wildfly_inheritance\src\main\config\wildfly does not exist
        at org.codehaus.plexus.util.DirectoryScanner.scan(DirectoryScanner.java:308)
        at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.getFilesToCopy(WarProjectPackagingTask.java:351)
        at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.copyResources(WarProjectPackagingTask.java:299)
        at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.handleWebResources(WarProjectPackagingTask.java:132)
        at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.performPackaging(WarProjectPackagingTask.java:83)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp(AbstractWarMojo.java:483)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp(AbstractWarMojo.java:411)
        at org.apache.maven.plugin.war.WarMojo.performPackaging(WarMojo.java:213)
        at org.apache.maven.plugin.war.WarMojo.execute(WarMojo.java:176)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 25 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
## [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

END LOG.

---

I reviewed settings.xml from mavenpath/conf/settings.xml
pluginGroups is empty:
## I Add 1 line "wildfly":

  <pluginGroups>
    
    <pluginGroup>org.wildfly.plugins</pluginGroup>  
##   </pluginGroups>

But I got the same result,

Please help me or fix pom.xml
thanks in advance.

**Comment by nromanetti** [comment]
I have just run it and it seems ok.
Could you please detail the steps you run?
In particular have you run the
mvn -Pdb,metadata,gen generate-sources
as explained in the bootstrap output
before running mvn -X wildfly:deploy ?

[INFO] Processing war project
[INFO] Copying webapp webResources [/Users/nromanetti/tmpbug/javaee7_wildfly_inheritance/src/main/config/wildfly] to [/Users/nromanetti/tmpbug/javaee7_wildfly_inheritance/target/javaee7_wildfly_inheritance]
[DEBUG] file application-ds.xml has a filtered file extension
[DEBUG] filtering /Users/nromanetti/tmpbug/javaee7_wildfly_inheritance/src/main/config/wildfly/application-ds.xml to /Users/nromanetti/tmpbug/javaee7_wildfly_inheritance/target/javaee7_wildfly_inheritance/WEB-INF/application-ds.xml

**Comment by wirelesss** [comment]
Thanks Nicolas,

I generated war file javaee7_wildfly_inheritance.war
but do you have any guide to deploy on wildfly?,
because when I go to wildfly URL:
It shows the following:
http://localhost:9990/console/App.html#standalone-deployments

javaee7_wildfly_inheritance.war

  Deployment is enabled

Details

```
Last enabled at 2016-06-07 04:14:54,623 CDT
The deployment was never disabled
Runtime name: javaee7_wildfly_inheritance.war
```

What is the URL application, or what previous steps are required
to display application on browser ?

thanks in advance

**Comment by nromanetti** [comment]
I think it is http://localhost:8080/javaee7_wildfly_inheritance

**Comment by wirelesss** [comment]
The response is Error 404:
`<html><head><title>Error</title></head><body>404 - Not Found</body></html>`

Please, do you have any tips to display the example of application "javaee7_wildfly_inheritance"?
thanks in advance

**Comment by nromanetti** [comment]
the console output says it is mapped on /application try
http://localhost:8080/application

If login does not work, try to add this dependency in your pom

``` xml
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-search-engine</artifactId>
            <version>5.5.0.Final</version>
            <scope>compile</scope>
        </dependency>
```

then undeploy:

```
mvn wildfly:undeploy
```

then redeploy

```
mvn wildfly:deploy
```

**Comment by wirelesss** [comment]
Thanks Nicolas,
but I get same results

I want to share you my server configuration ( installation ) and log , war files on Windows 10 -  64 bits

[to download](https://mega.nz/#!4kskADCK!MPwP0JLMrLBj3osCMYDMGi9-GjfSrxE87XpARRZiJmU)
It contains:
1-Directory project: c:\spring_wks_wildfly\javaee7_wildfly_inheritance\
2-Directory installation Wildfly server on c:\wildfly\wildfly-10.0.0.CR4\
3-War file: javaee7_wildfly_inheritance.war
4-LOG: 20160609_log_when_start_standalone.bat.txt
5-Screenshot: 2016-06-09 03_42_30-Error.png

Please can you review my configuration?
Otherwise can you share me your wildfly standalone server?

Thanks in advance
